// Golden applicants: the policy test set.
//
// Each case states the outcome the DEFAULT policy should produce and why,
// worked out from the rules and scorecard by hand before the engine was run.
// The test suite asserts the engine agrees, so any code change that moves a
// decision fails CI. The Policy tests page runs the same cases against the
// rules you have edited, to show which applicants a rule change would affect.
//
// Scores in `why` use the default weights: school tier 25, field 15,
// credit 20, income coverage 20, work experience 10, country risk 10.

const base = {
  citizenship: "IN",
  destination: "US",
  degreeLevel: "masters",
  fieldOfStudy: "stem",
  schoolTier: "1",
  monthsToGraduation: "18",
  loanAmount: "45000",
  householdIncome: "30000",
  creditHistory: "thin",
  workExpYears: "3",
  admitConfirmed: true,
};

const strong = {
  ...base,
  creditHistory: "established",
  householdIncome: "60000",
  loanAmount: "40000",
  workExpYears: "6",
};

export const SCENARIOS = [
  {
    id: "strong-prime",
    name: "Strong applicant",
    preset: true,
    summary: "Tier 1 STEM master's, established credit, income covers the loan",
    why: "Every factor at maximum: 25 + 15 + 20 + 20 + 10 + 10 = 100, above the band A floor of 80.",
    applicant: strong,
    expect: { decision: "APPROVED", stage: "full-pipeline", band: "A", score: 100 },
  },
  {
    id: "thin-file",
    name: "Thin credit file",
    preset: true,
    summary: "Tier 1 STEM master's, thin credit, $30K income for a $45K loan",
    why: "Thin credit scores 12 of 20 and income covers 44% of the target, 8.9 of 20. Total 79.4: approved in band B, just short of A.",
    applicant: base,
    expect: { decision: "APPROVED", stage: "full-pipeline", band: "B", score: 79.4 },
  },
  {
    id: "borderline-review",
    name: "Borderline",
    preset: true,
    summary: "Tier 3 school, other field, $15K income for a $60K loan",
    why: "10 + 8.3 + 20 + 3.3 + 6 + 7 = 54.6. Above the review line of 50, below approve at 65, so a credit analyst decides.",
    applicant: {
      ...base,
      citizenship: "BR",
      schoolTier: "3",
      fieldOfStudy: "other",
      creditHistory: "established",
      householdIncome: "15000",
      loanAmount: "60000",
      workExpYears: "1",
    },
    expect: { decision: "REVIEW", stage: "full-pipeline", score: 54.6 },
  },
  {
    id: "low-score-decline",
    name: "Low score",
    preset: true,
    summary: "Tier 3 MBA, thin credit, $15K income for a $100K loan",
    why: "10 + 12.1 + 12 + 2 + 6 + 7 = 49.1, just under the review line. Borrowing less would lift income coverage.",
    applicant: {
      ...base,
      citizenship: "VN",
      schoolTier: "3",
      degreeLevel: "mba",
      fieldOfStudy: "business",
      householdIncome: "15000",
      loanAmount: "100000",
      workExpYears: "1",
    },
    expect: { decision: "DECLINED", stage: "full-pipeline", score: 49.1 },
  },
  {
    id: "ineligible-multi",
    name: "Ineligible",
    preset: true,
    summary: "UK destination, admission not confirmed, unranked school",
    why: "Fails three knockout rules before any scoring: no UK partner, no confirmed admit, school below tier 3.",
    applicant: { ...strong, destination: "GB", admitConfirmed: false, schoolTier: "4" },
    expect: {
      decision: "DECLINED",
      stage: "eligibility",
      failedRules: ["supported-destination", "admit-confirmed", "school-tier"],
    },
  },
  {
    id: "entry-band",
    name: "Entry band",
    summary: "Tier 2 business masters, thin credit, $20K income for a $50K loan",
    why: "17.5 + 12.8 + 12 + 5.3 + 8.5 + 10 = 66.1: approved, but only in band C (65 to 69.9).",
    applicant: {
      ...base,
      schoolTier: "2",
      fieldOfStudy: "business",
      householdIncome: "20000",
      loanAmount: "50000",
    },
    expect: { decision: "APPROVED", stage: "full-pipeline", band: "C", score: 66.1 },
  },
  {
    id: "no-credit-history",
    name: "No credit history",
    summary: "Strong profile with no credit file at all",
    why: "No history scores 6 of 20, but school, field, income and experience carry it: 86, band A. The model underwrites future earnings, not past borrowing.",
    applicant: { ...strong, creditHistory: "none" },
    expect: { decision: "APPROVED", stage: "full-pipeline", band: "A", score: 86 },
  },
  {
    id: "medium-country-risk",
    name: "Medium country risk",
    summary: "Same as the thin-file case, citizen of a medium-risk country",
    why: "Country risk drops from 10 to 7, so 79.4 becomes 76.4. Still band B.",
    applicant: { ...base, citizenship: "NG" },
    expect: { decision: "APPROVED", stage: "full-pipeline", band: "B", score: 76.4 },
  },
  {
    id: "phd-no-income",
    name: "PhD, no household income",
    summary: "Tier 2 medicine PhD, established credit, zero income",
    why: "17.5 + 15 + 20 + 0 + 6 + 10 = 68.5. Approved in band C with no income support at all.",
    applicant: {
      ...base,
      citizenship: "CN",
      degreeLevel: "phd",
      fieldOfStudy: "medicine",
      schoolTier: "2",
      creditHistory: "established",
      householdIncome: "0",
      workExpYears: "1",
    },
    expect: { decision: "APPROVED", stage: "full-pipeline", band: "C", score: 68.5 },
  },
  {
    id: "canada-routing",
    name: "Canada destination",
    summary: "Strong applicant studying in Canada",
    why: "Scores 100 like the strong case and routes to the Canada partner, not the US one.",
    applicant: { ...strong, destination: "CA" },
    expect: { decision: "APPROVED", stage: "full-pipeline", band: "A", partner: "partner-ca" },
  },
  {
    id: "undergrad-rule-off",
    name: "Undergraduate",
    summary: "Tier 1 STEM undergraduate, graduate-only rule switched off",
    why: "The graduate-only rule is disabled by default, so it is skipped. Field score falls to 10.5 (0.7 multiplier) and zero experience scores 4: 89.5, band A.",
    applicant: { ...strong, degreeLevel: "undergraduate", workExpYears: "0" },
    expect: { decision: "APPROVED", stage: "full-pipeline", band: "A", score: 89.5 },
  },
  {
    id: "amount-below-floor",
    name: "Below the loan floor",
    summary: "Strong applicant asking for $3,000",
    why: "The floor is $5,000, so the amount rule knocks it out before scoring.",
    applicant: { ...strong, loanAmount: "3000" },
    expect: { decision: "DECLINED", stage: "eligibility", failedRules: ["amount-range"] },
  },
  {
    id: "amount-at-floor",
    name: "Exactly at the floor",
    summary: "Strong applicant asking for exactly $5,000",
    why: "The floor is inclusive, so $5,000 passes and the profile scores 100.",
    applicant: { ...strong, loanAmount: "5000" },
    expect: { decision: "APPROVED", stage: "full-pipeline", band: "A", score: 100 },
  },
  {
    id: "amount-at-ceiling",
    name: "Exactly at the ceiling",
    summary: "Strong applicant asking for exactly $100,000",
    why: "The ceiling is inclusive. Income now covers 40% of the target, 8 of 20: total 88, band A.",
    applicant: { ...strong, loanAmount: "100000" },
    expect: { decision: "APPROVED", stage: "full-pipeline", band: "A", score: 88 },
  },
  {
    id: "amount-above-ceiling",
    name: "Above the loan ceiling",
    summary: "Strong applicant asking for $150,000",
    why: "Above the $100,000 ceiling, so the amount rule declines it.",
    applicant: { ...strong, loanAmount: "150000" },
    expect: { decision: "DECLINED", stage: "eligibility", failedRules: ["amount-range"] },
  },
  {
    id: "unsupported-destination",
    name: "UK destination",
    summary: "Strong applicant studying in the UK",
    why: "No active UK partner, so the destination rule declines it.",
    applicant: { ...strong, destination: "GB" },
    expect: { decision: "DECLINED", stage: "eligibility", failedRules: ["supported-destination"] },
  },
  {
    id: "no-admit",
    name: "Admission not confirmed",
    summary: "Strong applicant without a confirmed admit",
    why: "A confirmed admit is a hard requirement.",
    applicant: { ...strong, admitConfirmed: false },
    expect: { decision: "DECLINED", stage: "eligibility", failedRules: ["admit-confirmed"] },
  },
  {
    id: "already-graduated",
    name: "Already graduated",
    summary: "Strong applicant whose program has ended",
    why: "Expected graduation must be in the future.",
    applicant: { ...strong, monthsToGraduation: "-3" },
    expect: { decision: "DECLINED", stage: "eligibility", failedRules: ["enrollment-window"] },
  },
  {
    id: "graduation-too-far",
    name: "Graduation 5 years out",
    summary: "Strong applicant graduating in 60 months",
    why: "The enrollment window is 48 months. Income that far out is too distant to underwrite.",
    applicant: { ...strong, monthsToGraduation: "60" },
    expect: { decision: "DECLINED", stage: "eligibility", failedRules: ["enrollment-window"] },
  },
  {
    id: "graduation-at-window",
    name: "Graduation exactly 48 months out",
    summary: "Strong applicant at the edge of the enrollment window",
    why: "The 48-month window is inclusive, so it passes and scores 100.",
    applicant: { ...strong, monthsToGraduation: "48" },
    expect: { decision: "APPROVED", stage: "full-pipeline", band: "A", score: 100 },
  },
  {
    id: "unranked-school",
    name: "Unranked school",
    summary: "Strong applicant at an unranked school",
    why: "The minimum is tier 3, so an unranked school (tier 4) is declined.",
    applicant: { ...strong, schoolTier: "4" },
    expect: { decision: "DECLINED", stage: "eligibility", failedRules: ["school-tier"] },
  },
];

export const PRESETS = SCENARIOS.filter((s) => s.preset);

export function scenarioById(id) {
  return SCENARIOS.find((s) => s.id === id) || null;
}
